### ISSUE TITLE
Build error since the board file for BOARD_SPARKFUN_NRF52840_MINI is missing and not defined in the default boards.h

### ISSUE THREAD

**Issue by anusha194** [otaviojr/zigbee_light_sensor#1]
On performing build using make as per the provided instructions, I get the following error:

make
mkdir _build
cd _build && mkdir nrf52840_xxaa
Assembling file: gcc_startup_nrf52840.S
Compiling file: nrf_log_backend_serial.c
Compiling file: nrf_log_backend_uart.c
Compiling file: nrf_log_default_backends.c
Compiling file: nrf_log_frontend.c
Compiling file: nrf_log_str_formatter.c
Compiling file: boards.c
In file included from ../../../../../components/boards/boards.c:40:0:
../../../../../components/boards/boards.h:87:2: error: #error "Board is not defi
ned"
 #error "Board is not defined"
  ^~~~~
make: *** [../../../../../components/toolchain/gcc/Makefile.common:272: _build/nrf52840_xxaa/boards.c.o] Error 1

This is due to the fact that the board defined in Makefile is BOARD_SPARKFUN_NRF52840_MINI but boards.h is taken directly from the SDK and not modified for this particular board.

**Comment by otaviojr** [comment]
Hi, I've made some changes and upload it. Could you try again?

I've changed the project to act as a router since I used it with a power source, so it could help expanding my network.

regards,
Otávio Ribeiro

**Comment by otaviojr** [comment]
You will see inside the project a folter named "patch".

Inside it you will have a patch file for the board.h file (board.h.patch) and a header for sparkfun board.

The original boards.h file will be at <SDK_ROOT>/components/boards directory. Just apply the patch and copy the header to the same location.

regards,
Otávio Ribeiro
